import { FormEvent, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Braces, Check, Code2, Download, ExternalLink, GitBranch, Layers3, Mail, Menu, Plus, Send, Sparkles, X } from 'lucide-react'
import { projects, sampleXML, starterPost, type Post } from './data'

const nav = ['Work', 'Writing', 'Experience', 'Contact']
const skills = [{ label: 'Product engineering', value: 94 }, { label: 'System design', value: 88 }, { label: 'Frontend architecture', value: 91 }, { label: 'Cloud platforms', value: 82 }]

function ImportModal({ onClose, onImport }: { onClose: () => void; onImport: (post: Post) => void }) {
  const [xml, setXml] = useState(sampleXML); const [error, setError] = useState(''); const [done, setDone] = useState(false)
  const importPost = () => {
    const doc = new DOMParser().parseFromString(xml, 'application/xml');
    if (doc.querySelector('parsererror')) return setError('This XML could not be parsed. Check that all required tags are closed.')
    const get = (key: string) => doc.querySelector(key)?.textContent?.trim() || ''
    const fields = ['title', 'category', 'date', 'tags', 'summary', 'content']; if (fields.some((field) => !get(field))) return setError('Please include title, category, date, tags, summary, and content.')
    onImport({ title: get('title'), category: get('category'), date: get('date'), tags: get('tags').split(',').map((tag) => tag.trim()).filter(Boolean), summary: get('summary'), content: get('content') }); setDone(true); setTimeout(onClose, 700)
  }
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4 backdrop-blur-sm">
    <motion.div initial={{ y: 18, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="w-full max-w-3xl rounded-3xl border border-white/10 bg-[#0b1827] p-6 shadow-2xl sm:p-8">
      <div className="mb-6 flex items-start justify-between"><div><p className="eyebrow">Author workspace</p><h2 className="mt-2 text-2xl font-bold">Import post via XML</h2><p className="mt-2 text-sm text-slate-400">Paste a post using the included schema. CDATA content supports HTML or Markdown.</p></div><button className="icon-button" onClick={onClose} aria-label="Close importer"><X size={20}/></button></div>
      <textarea value={xml} onChange={(e) => { setXml(e.target.value); setError('') }} className="h-80 w-full rounded-2xl border border-white/10 bg-slate-950/50 p-4 font-mono text-xs leading-6 text-cyan-100 outline-none focus:border-cyan-300" aria-label="XML post content" />
      {error && <p className="mt-3 text-sm text-rose-300">{error}</p>}<div className="mt-6 flex flex-wrap items-center justify-between gap-3"><button onClick={() => setXml(sampleXML)} className="text-sm font-semibold text-cyan-300 hover:text-cyan-100">Restore sample post</button><button onClick={importPost} className="button-primary">{done ? <><Check size={17}/> Imported</> : <><Braces size={17}/> Parse & publish</>}</button></div>
    </motion.div></motion.div>
}

export default function App() {
  const [activeProject, setActiveProject] = useState('All work'); const [posts, setPosts] = useState<Post[]>([starterPost]); const [activePost, setActivePost] = useState('All posts'); const [importOpen, setImportOpen] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [sent, setSent] = useState(false)
  const categories = ['All posts', ...Array.from(new Set(posts.map((post) => post.category)))]; const postList = activePost === 'All posts' ? posts : posts.filter((post) => post.category === activePost); const projectCategories = ['All work', ...Array.from(new Set(projects.map((project) => project.category)))]; const shownProjects = activeProject === 'All work' ? projects : projects.filter((project) => project.category === activeProject)
  const importPost = (post: Post) => { setPosts((current) => [post, ...current]); setActivePost('All posts') }
  const submitContact = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; if (form.checkValidity()) { setSent(true); form.reset() } }
  return <main className="overflow-hidden"><div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <header className="relative z-20 mx-auto flex max-w-6xl items-center justify-between px-5 py-6 lg:px-8"><a href="#top" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-cyan text-slate-950"><Code2 size={18}/></span>mira<span className="text-cyan">.</span>dev</a><nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex">{nav.map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="transition hover:text-cyan">{item}</a>)}<button onClick={() => setImportOpen(true)} className="button-small"><Plus size={15}/> Import XML</button></nav><button onClick={() => setMenuOpen(!menuOpen)} className="icon-button md:hidden"><Menu size={20}/></button>{menuOpen && <div className="absolute right-5 top-16 grid gap-3 rounded-2xl border border-white/10 bg-panel p-5 md:hidden">{nav.map((item) => <a onClick={() => setMenuOpen(false)} href={`#${item.toLowerCase()}`} key={item}>{item}</a>)}<button onClick={() => setImportOpen(true)} className="text-left text-cyan">Import XML</button></div>}</header>
    <section id="top" className="relative mx-auto grid max-w-6xl gap-12 px-5 pb-24 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:pb-36 lg:pt-24"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><p className="eyebrow"><Sparkles size={14}/> Available for select collaborations</p><h1 className="mt-7 max-w-3xl text-5xl font-extrabold tracking-[-.055em] text-white sm:text-7xl">Building digital products with <span className="text-gradient">clarity &amp; character.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">I’m Mira Khan, a full-stack engineer who turns complex systems into elegant, durable experiences for people and teams.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#work" className="button-primary">Explore selected work <ArrowDownRight size={18}/></a><a href="mailto:hello@mirakhan.dev" className="button-secondary"><Mail size={17}/> Start a conversation</a></div><a href="/resume.pdf" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-cyan"><Download size={16}/> Download résumé</a></motion.div>
      <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .15 }} className="hero-card relative min-h-96 overflow-hidden rounded-3xl border border-white/10 p-7"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_12%,rgba(67,232,222,.26),transparent_25rem)]"/><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between text-sm text-slate-400"><span>Currently exploring</span><span className="pulse-dot"/></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan">A pragmatic toolkit</p><div className="mt-5 flex flex-wrap gap-2">{['React', 'Python', 'Django', 'Cloud architecture', 'TypeScript', 'Design systems'].map((tech) => <span className="tech-pill" key={tech}>{tech}</span>)}</div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-sm font-semibold">Independent by default.</p><p className="mt-1 text-sm leading-6 text-slate-400">Working across product strategy, interface craft, and resilient backend systems.</p></div></div></motion.div></section>
    <section id="work" className="section-shell"><div className="section-heading"><div><p className="eyebrow">Selected work</p><h2>Thoughtful from every angle.</h2></div><p>Selected product work across teams that value purposeful decisions and uncommon attention to detail.</p></div><div className="filter-row">{projectCategories.map((category) => <button key={category} onClick={() => setActiveProject(category)} className={activeProject === category ? 'filter active' : 'filter'}>{category}</button>)}</div><div className="mt-8 grid gap-5 md:grid-cols-3">{shownProjects.map((project, index) => <motion.article layout initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} key={project.title} className="project-card"><div className={`h-44 rounded-2xl bg-gradient-to-br ${project.color} p-5`}><div className="flex h-full items-end justify-between"><span className="rounded-full border border-white/10 bg-slate-950/40 px-3 py-1 text-xs">0{index + 1}</span><Layers3 className="text-cyan/80" size={32}/></div></div><p className="mt-5 text-xs font-semibold uppercase tracking-widest text-cyan">{project.category}</p><h3 className="mt-2 text-xl font-bold">{project.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.stack.map((tag) => <span key={tag} className="tag">{tag}</span>)}</div><div className="mt-6 flex gap-4 text-sm font-semibold"><a href={project.live} className="inline-flex items-center gap-1 hover:text-cyan">Preview <ExternalLink size={14}/></a><a href={project.repo} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-slate-400 hover:text-white">Code <GitBranch size={14}/></a></div></motion.article>)}</div></section>
    <section id="writing" className="section-shell pt-24"><div className="section-heading"><div><p className="eyebrow">Notes &amp; ideas</p><h2>Writing from the work.</h2></div><button onClick={() => setImportOpen(true)} className="button-secondary"><Braces size={17}/> Import post via XML</button></div><div className="filter-row">{categories.map((category) => <button key={category} onClick={() => setActivePost(category)} className={activePost === category ? 'filter active' : 'filter'}>{category}</button>)}</div><div className="mt-8 grid gap-4">{postList.map((post) => <article className="post-card" key={`${post.title}-${post.date}`}><div><p className="text-xs font-semibold uppercase tracking-widest text-cyan">{post.category} <span className="ml-2 text-slate-500">· {post.date}</span></p><h3>{post.title}</h3><p>{post.summary}</p><div className="mt-4 flex flex-wrap gap-2">{post.tags.map((tag) => <span className="tag" key={tag}>#{tag}</span>)}</div></div><ArrowUpRight className="mt-1 shrink-0 text-cyan"/></article>)}</div></section>
    <section id="experience" className="section-shell grid gap-12 py-24 lg:grid-cols-2"><div><p className="eyebrow">Experience</p><h2 className="section-title">Built in the details.</h2><div className="timeline"><div><p className="text-cyan">2023 — now</p><h3>Independent product engineer</h3><p>Partnering with ambitious teams from first sketch to scalable production systems.</p></div><div><p className="text-cyan">2020 — 2023</p><h3>Senior engineer · Lumen Labs</h3><p>Led the frontend platform and design-system practice for an analytics suite.</p></div><div><p className="text-cyan">2017 — 2020</p><h3>Software engineer · Northstar</h3><p>Designed reliable workflows for operations teams navigating complex data.</p></div></div></div><div className="skills-card"><p className="eyebrow">Capabilities</p><h2 className="section-title">Technical, but human.</h2><div className="mt-9 space-y-6">{skills.map((skill) => <div key={skill.label}><div className="mb-2 flex justify-between text-sm"><span>{skill.label}</span><span className="text-cyan">{skill.value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><motion.div initial={{ width: 0 }} whileInView={{ width: `${skill.value}%` }} viewport={{ once: true }} transition={{ duration: .9 }} className="h-full rounded-full bg-gradient-to-r from-cyan to-emerald-300"/></div></div>)}</div></div></section>
    <section id="contact" className="section-shell pb-24"><div className="contact-panel"><div><p className="eyebrow">Let’s build something useful</p><h2>Have a good problem?</h2><p className="mt-4 max-w-md leading-7 text-slate-400">Tell me a little about it. I’ll reply within two working days with a thoughtful next step.</p><div className="mt-8 flex gap-3"><a className="social" href="https://github.com" aria-label="GitHub"><GitBranch size={19}/></a><a className="social" href="mailto:hello@mirakhan.dev" aria-label="Email"><Mail size={19}/></a></div></div><form onSubmit={submitContact} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><input required name="name" placeholder="Your name"/><input required type="email" name="email" placeholder="Email address"/></div><textarea required minLength={12} name="message" placeholder="A little about your project" className="min-h-32"/><button className="button-primary w-fit" type="submit">{sent ? <><Check size={17}/> Message ready</> : <><Send size={17}/> Send inquiry</>}</button></form></div></section>
    <footer className="border-t border-white/5 py-7 text-center text-sm text-slate-500">© 2026 Mira Khan. Designed and engineered with intention.</footer><AnimatePresence>{importOpen && <ImportModal onClose={() => setImportOpen(false)} onImport={importPost}/>}</AnimatePresence>
  </main>
}
